import { useState } from "react";
import styles from "./attend.module.css";
import {reasonsGeneratedByUs,reasonsGeneratedByGPT} from './attendList';
import { ReactComponent as Circles } from "../../images/circles.svg";
import { ReactComponent as Ean } from "../../images/eanSmall.svg";
import { ReactComponent as Plus } from "../../images/plusSmall.svg";
import AngleWhite from "../../images/angleWhite.png";


export default function Attend() {

const [current, setCurrent]=useState(0);
const [reasons, setReasons] = useState(reasonsGeneratedByUs)

const currentSlide =(index)=>{
    setCurrent(index)
    console.log('current',current)
 }


  return (
<div className={styles.attendContainer}>
<h2 className={styles.title}>why should i attend?</h2>
<div className={styles.choiceWrapper}>
<div className={styles.plusContainer} onClick={()=>(setReasons(reasonsGeneratedByUs), setCurrent(0))}>
<div className={styles.choice}><Plus className={reasons===reasonsGeneratedByUs? (styles.plusActive):(styles.plus)}/></div>
Reasons generated by us

</div>
<div className={styles.plusContainer } onClick={()=>(setReasons(reasonsGeneratedByGPT), setCurrent(0))}>
<div className={styles.choice}><Plus className={reasons===reasonsGeneratedByGPT? (styles.plusActive):(styles.plus)}/></div>
Reasons generated by GPT-J-6b model
</div>
</div>
<div className={styles.slider}>
<div className={styles.sliderCountTop}>
  {reasons.map((slide, index)=>{
           return(
           <div className={index===current ? (styles.variantTitleActive):(styles.variantTitle)} onClick={()=>currentSlide(index)} key={index}>
            <span >{Object.keys(slide)}</span>
            <img
            className={index === current? (styles.ungleWhite): (styles.ungleWhiteHide)}
            src={AngleWhite}
            alt="decoration"
          ></img>
          </div>)
       })}
  </div>
<div className={styles.attendContent}>
{reasons.map((slide, index)=>{
    return(
        <div className={index===current? (styles.variantActive):(styles.variant)} key={index}>
        {index === current &&(
            <>
        <div className={styles.info}>
           <span className={styles.attendInfo}>{Object.values(slide)}</span>
                <div className={styles.icons}>
                <Circles className={styles.circles}/>
                <Ean className={styles.ean}/>
                </div>
        </div>
            </>
        )}
      </div>
    )
})}
</div>
  <div className={styles.sliderCount}>
  {reasons.map((slide, index)=>{
           return(
           <div className={index===current ? (styles.variantTitleActive):(styles.variantTitle)} onClick={()=>currentSlide(index)} key={index}>
            <span >{Object.keys(slide)}</span>
          </div>)
       })}
  </div>

   </div>

</div>
  )
}
